<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="TCERCcons09" ignored="0" tests="1" failures="1" timestamp="2022-02-13T18:13:13 EET" time="55.994" errors="0">
  <testcase name="checkCorrectRestaurant" time="36.406" classname="addingToFavorites">
    <failure type="java.lang.AssertionError" message="Added restaurant couldn&amp;apos;t find under favorites!!">
      <![CDATA[java.lang.AssertionError: Added restaurant couldn't find under favorites!!
at pages.HomePage.readFavorites(HomePage.java:132)
at addingToFavorites.checkCorrectRestaurant(addingToFavorites.java:27)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- checkCorrectRestaurant -->
</testsuite>
